### ISSUE TITLE
Profiler report leaks passwords on Jenkins

### ISSUE THREAD

**Issue by jakub-bochenski** [jcgay/maven-profiler#11]
This is an unfortunate interaction between the  "parameters" attribute and the way Maven Integration Plugin (`Invoke Top-Level Maven targets`) works on Jenkins.
For unknown reasons (I think it's a "feature") Mask Passwords Plugin will append all passwords as `-D` arguments to the Maven invocation.

TL;DR would it be possible to disable dumping parameters via a param switch? I know I can edit the file later but it's a hassle

**Comment by jcgay** [comment]
Sure, if you're willing to contribute it I'll be glad to merge it :)

Or I will just have a look at it during holidays next week :p

**Comment by jakub-bochenski** [comment]
OK, I will try to send a PR some time next week

**Comment by jakub-bochenski** [comment]
There is a fix available for this in Jenkins, so I no longer need it: https://issues.jenkins-ci.org/browse/JENKINS-40636
I've sent you some other PRs though

**Comment by jcgay** [comment]
Thanks for the explanation !

**Comment by kutschkem** [comment]
This is now relevant to me, as I pass credentials to the maven jarsigner, which get output on the profiling report.

Here is what I do in Jenkins:

 ```
  withCredentials([string(credentialsId: 'jarsignerKeypass', variable: 'jarsignerKeypass'), string(credentialsId: 'jarsignerStorepass', variable: 'jarsignerStorepass'), string(credentialsId: 'jarsignerAlias', variable: 'jarsignerAlias')]) {
	sh """#!/bin/bash					
	  mvn verify -Djarsigner.keystore='~/Jenkins/mykeystore' -Djarsigner.keypass='${jarsignerKeypass}' -Djarsigner.storepass='${jarsignerStorepass}' -Djarsigner.alias='${jarsignerAlias}' -Dprofile
	"""
```

An option to not show the parameters would be welcome.

**Comment by jakub-bochenski** [comment]
@kutschkem as a workaround you could instead define the values in pom.xml by referencing `${env.jarsignerKeypass}` etc.  Requiring a pom.xml change is not ideal though.

**Comment by jcgay** [comment]
Ok sounds fair to me, anyone willing to contribute it ?
