### ISSUE TITLE
Does not work on Jenkins (maven-plugin)

### ISSUE THREAD

**Issue by danieldestro** [jcgay/maven-profiler#15]
I am able to run properly on command line when copying the JAR file to Maven lib/ext dir.
But when running on Jenkins with Maven-plugin it does not work at all. Jenkins and the plugin does not recognize the JAR in lib/ext, not even on lib dir.
What can I do to get it working on Jenkins (2.32.2)?

**Comment by danieldestro** [comment]
Tried this and it did not work either: https://groups.google.com/forum/#!topic/jenkinsci-users/InTM6LN43aU

**Comment by jcgay** [comment]
I know it works with Jenkins freestyle project but the Maven style jobs are treated differently in Jenkins.  
Based on these issues https://issues.jenkins-ci.org/browse/JENKINS-28629 and https://issues.jenkins-ci.org/browse/JENKINS-30058 it seems broken for now.

**Comment by jakub-bochenski** [comment]
We use the profiler for jenkins builds.

Unfortunately it will work only with the "Invoke Top-Level Maven Targets" steps.
It will NOT work in the main step of the Maven job though.

A cheap migration path for Maven jobs is as follows. 
Run some noop like `help:evaluate` in the main Maven job and then move the actual processing to a "Post Build Step" section.

**Comment by jakub-bochenski** [comment]
I wanted to upload a screenshot to illustrate, but github keeps failing with "Something went really wrong, and we can’t process that file."

**Comment by jcgay** [comment]
Feel free to re-open if it's still actual.
