### ISSUE TITLE
Request to use `target/...` for destination directory rather than `.profiler`

### ISSUE THREAD

**Issue by binkley** [jcgay/maven-profiler#16]
Hi, thanks for a lovely plugin!

Would you consider using `target/site/profiler` (or similar under `target/`) as the destination for reports?  I'd like to integrate profiler reporting into the regular site generation.

Also, `maven clean` doesn't delete old reports (but I'm assuming you know that :) ).

I browsed the source and a setting for the destination directory didn't jump out at me.

**Comment by jcgay** [comment]
Thanks for the kind words :)

In fact the `.profiler` folder which is not cleaned is wanted :p  
As I'm using this extension to compare different `mvn` run, I need to write reports somewhere that will not be clean between builds.  

But I can introduce a property to customize report directory, will it be find for you ?

**Comment by binkley** [comment]
Yes, please.  This looks just like what I want.

Comparing profile results between runs is sensible most of the time.  For my purposes, I only want the one time.  Thanks!

**Comment by jcgay** [comment]
Can you give a try to the latest release ?
Thx

**Comment by binkley** [comment]
I'm happy!

https://github.com/binkley/labs/commit/ef4fd9f729a7cc0b85b494aeaa63a6aabdec58ac
